### ISSUE TITLE
Librerías y frameworks recomendados

### ISSUE THREAD

**Issue by sergiodxa** [sergiodxa/impresionante-javascript#48]
Que tal crear una categoría para listar librerías recomendadas? que cada librería solucione un problema y crear una lista de librerías recomendadas para solucionar X problemas, por ejemplo React para vista, Redux para manejo de datos, etc. y discutir siempre cada librería para decidir la que consideramos mejor

cc .@yeion7

**Comment by sergiodxa** [comment]
La idea sería crear una lista para principiantes que les recomiende que usar, por ejemplo si quieren trabajar con fechas se les recomienda seguramente `moment` que es lo mejor que he visto.

Y si alguien conoce otra opción se propone en un PR y se discute si es mejor o no.

**Comment by yeion7** [comment]
Me parece una excelente idea, pero cada libreria tendría un link a un recurso en español de como utilizarla?

**Comment by sergiodxa** [comment]
Sería ideal complementarla con links en español, que podrían estar en la lista de artículos. Yo lo que digo es crear una lista con los links a npm, no estarían en español, pero la ideal es dar recomendaciones, porque quien llegue acá y no sabe nada no va a saber que librerías usar y todas están en inglés, siempre.

**Comment by yeion7** [comment]
Pero el objetivo del repositorio es crear recopilación de recursos en español para aprender JavaScript, no me cuadra, pero podríamos manejarlo en un repositorio aparte y lo vinculamos en este. 

Donde el objetivo podría ser plantear problemas y librerías para solucionarlos o una lista de librerías como lo plateas, así cada repositorio tiene un fin muy especifico.
